### ISSUE TITLE
Package 'mysql-client' has no installation candidate

### ISSUE THREAD

**Issue by iplat64** [Blueowner/docker-compose-laravel#1]
It appears that building the image fails with the following error:

Package mysql-client is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'mysql-client' has no installation candidate
ERROR: Service 'php-fpm' failed to build: The command '/bin/sh -c apt-get update &&     apt-get install -y mysql-client &&     pecl install xdebug &&     docker-php-ext-install pdo_mysql &&     docker-php-ext-enable xdebug' returned a non-zero code: 100

**Comment by serafinomb** [comment]
Hello @iplat64,
I've just tried to rebuild the images and could not reproduce the issue.

These are the steps I followed:
* create a new directory: `mkdir docker-compose-laravel-issue-1` and `cd` into it
* create a `public/index.html` file: `echo "Hello world" > public/index.html`
* clone the repository into .docker: `git clone <repository url> .docker`
* build the images from within the .docker directory: `(cd .docker && dcp build --no-cache)` 
* visit http://website.localhost/

Can you try again and let me know if you still get an error please?
